spring:
  application:
    name: blog
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/blog
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
      show-sql: true
      generate-ddl: true
    sql:
      init:
        mode: always
server:
  port: 8080